import { Product } from "@/types/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Mouse VXE RX",
    tag: "Eletrônicos",
    costPrice: 180,
    salePrice: 350,
    currency: "BRL",
    quantity: 3,
    category: "fisico",
    status: "em_estoque",
    createdAt: "2026-03-10T10:00:00.000Z",
  },
  {
    id: "2",
    name: "Pet Neon Fly",
    tag: "Digital / Roblox",
    costPrice: 5,
    salePrice: 9,
    currency: "USD",
    quantity: 1,
    category: "digital",
    status: "em_estoque",
    createdAt: "2026-03-11T11:00:00.000Z",
  },
  {
    id: "3",
    name: "Teclado Mecânico",
    tag: "Eletrônicos",
    costPrice: 220,
    salePrice: 390,
    currency: "BRL",
    quantity: 2,
    category: "fisico",
    status: "em_estoque",
    createdAt: "2026-03-12T12:00:00.000Z",
  },
  {
    id: "4",
    name: "Headset Gamer",
    tag: "Eletrônicos",
    costPrice: 150,
    salePrice: 220,
    currency: "BRL",
    quantity: 1,
    category: "fisico",
    status: "vendido",
    createdAt: "2026-03-13T13:00:00.000Z",
  },
  {
    id: "5",
    name: "Gamepass Ultimate",
    tag: "Digital / Xbox",
    costPrice: 8,
    salePrice: 14,
    currency: "USD",
    quantity: 2,
    category: "digital",
    status: "em_estoque",
    createdAt: "2026-03-14T14:00:00.000Z",
  },
];

export const weeklyPerformance = [
  { label: "Seg", value: 320 },
  { label: "Ter", value: 480 },
  { label: "Qua", value: 210 },
  { label: "Qui", value: 590 },
  { label: "Sex", value: 430 },
  { label: "Sáb", value: 780 },
  { label: "Dom", value: 610 },
];

export const monthlySales = [
  { label: "Jan", value: 420 },
  { label: "Fev", value: 580 },
  { label: "Mar", value: 390 },
  { label: "Abr", value: 720 },
  { label: "Mai", value: 850 },
  { label: "Jun", value: 930 },
  { label: "Jul", value: 810 },
];
